### ISSUE TITLE
classification

### ISSUE THREAD

**Issue by ghost** [philipperufin/eepypr#1]
Hi Philipe,
I'm highly interested in your processing framework for NICFI data. Thank you very much for that.
Can you also share the code, which was used to calculate texture metrics and classifiy the images?

**Comment by philipperufin** [comment]
Hi @spengli-berlin, 
You can find the code for calculating texture metrics in /src/txt.py, they can be used as any of the STM functions. The classification in the paper was done using GEEs smileRandomForest. Model training and prediction are a few lines of code only, please see the documentation here: https://developers.google.com/earth-engine/apidocs/ee-classifier-smilerandomforest. Hope this helps, reach out if you need more info.
